# https://taskfile.dev
version: "3"

includes:
  setup: ./tasks/Taskfile.setup.yml
  docs: ./tasks/Taskfile.docs.yml

tasks:
  default:
    silent: true
    cmds:
      - echo "Awesome Docs"
      - task -l